checks:
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-lines:
    enabled: true
    config:
      threshold: 40
  method-count:
    enabled: true
    config:
      threshold: 40
  method-complexity:
    enabled: true
    config:
      threshold: 5
  similar-code:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 65
exclude_patterns:
  - '**/test/'
  - '**/pageObjects/'
  - '**/node_modules/'
  - 'node_modules/'
