checks:
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-lines:
    enabled: true
    config:
      threshold: 40
  method-count:
    enabled: true
    config:
      threshold: 40
exclude_patterns:
  - 'src/test/'
  - 'src/pageObjects/'
  - 'node_modules/'
