# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  ACT_NODE_VERSION: 14
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.ACT_NODE_VERSION}}
      - name: Install dependences
        run: |
          npm i 
          npm i appium
      - name: Run test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-options: -no-snapshot-save -no-boot-anim
          script: |
            kill -9 $(lsof -t -i:4723) || true
            while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 1; done
            ./node_modules/.bin/appium -p 4725 --log-level error & APPIUM_PID=$!
            adb devices
            adb install ./app/com.monefy.apk
            sleep 3
            adb shell input keyevent 26
            sleep 1
            adb shell input swipe 200 500 200 0
            npm run test:app
            kill -9 $APPIUM_PID || true
      - name: Stop Appium
        if: ${{ always() }}
        run: |
          sleep 3
          kill -9 $(lsof -t -i:4723) || true
      - name: Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ./reports/coverage/lcov-report/
            ./reports/*.html
      - name: Publish code coverage
        if: ${{ always() }}
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/reports/coverage/lcov.info:lcov
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          tag_prefix: ~
          default_bump: minor
          release_branches: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: print tag
        run: echo ${{ steps.create_tag.outputs.new_tag }}
      - name: get commit message
        run: |
          echo ::set-env name=COMMIT_MSG::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run: |
          echo * Last commit: ${{ env.COMMIT_MSG }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.create_tag.outputs.new_version }}
          release_name: Release ${{ steps.create_tag.outputs.new_version }}
          body: |
            Release notes:
            - ${{ env.COMMIT_MSG }}
          draft: false
          prerelease: false
